app/models.py
from app import db
from datetime import datetime
import re
import email_validator

from flask_security import UserMixin, RoleMixin


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags', 
                        db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                        db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                        )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '{}'.format( self.name)

    def generate_slug(self):
        if self.name:
            self.slug = slugify(self.name)


# Flask security #

roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
    )

class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

app/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import Configuration
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore, Security, current_user

from flask import redirect, url_for, request

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

# ADMIN #
from models import *

class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url ))


class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)

class AdminView(AdminMixin, ModelView):
    pass

class HomeAdminView(AdminMixin, AdminIndexView):
    pass

class PostAdminView(AdminMixin, BaseModelView):
    pass

class TagAdminView(AdminMixin, BaseModelView):
    pass


admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))
admin.add_view(AdminView(User, db.session))
admin.add_view(AdminView(Role, db.session))


# Flask security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

app/main.py
from app import app
from app import db
from posts.blueprint import posts
import view

app.register_blueprint(posts, url_prefix='/blog')
if __name__ == '__main__':
    app.run(debug=True)

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Post, Tag
from flask import request
from .forms import PostForm
from app import db
from flask import redirect, url_for

from flask_security import login_required


posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body = body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Что-то пошло не так')
        return redirect(url_for('posts.index'))
    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)



@posts.route('/')
def index():
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)).all()
    else:
        posts = Post.query.order_by(Post.created.desc())
    return render_template('posts/index.html', posts=posts)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

    
@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', posts=posts, tag=tag)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Написать пост
{% endblock %}

{% block content_title %}
   <h1 class="display-4 col-md-6">
      Написать пост:
  </h1>
{% endblock %}

{% block content %}

    <div class="col-md-6 shadow p-3 mb-5 bg-white rounded">
        <form action="{{ url_for('posts.create_post')}}" method="POST">

            {% for field in form %}
            <div class="form-group">
                {{ field.label(class="form-control-label") }}
                {{ field(class="form-control") }}
            </div>
            {% endfor %}

            <button type="submit" class="btn btn-outline-success">Создать</button>
        </form>
    </div>

{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Написать пост
{% endblock %}

{% block content_title %}
    <h1 class="display-4 col-md-6">
        Редактировать пост:
    </h1>
{% endblock %}

{% block content %}

    <div class="col-md-6 shadow p-3 mb-5 bg-white rounded">
        <form action="{{ url_for('posts.edit_post', slug=post.slug)}}" method="POST">

            {% for field in form %}
            <div class="form-group">
                {{ field.label(class="form-control-label") }}
                {{ field(class="form-control") }}
            </div>
            {% endfor %}

            <button type="submit" class="btn btn-outline-success">Сохранить изменения</button>
        </form>
    </div>

{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block  title %}
    Blueprint index page
{% endblock  %}

{% block  content_title %}
    <div class="container">
        <div class="row">
            <div class="col">
                <p class="text-center font-weight-normal">Посты</p>
            </div>
        </div>
    </div>
{% endblock  %}

{% block  content %}

{% for post in posts %}
<div class="d-flex justify-content-center">
    <div class="card mb-3 shadow p-3 mb-5 bg-white rounded col md-offset-4 " style="max-width: 540px;">
        <div class="row">
            <div class="col-md-4 col">
                <img src="https://mykaleidoscope.ru/uploads/posts/2019-12/1575766848_18-19.jpg" class="card-img"
                    alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body col-md-offset-4">

                    <h5 class="card-title">
                        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
                            <p class="font-weight-normal">{{ post.title }}</p>
                        </a>
                    </h5>

                    <p class="card-text">{{post.body}}</p>
                    <p class="card-text"><small class="text-muted">Изменен {{ post.created}}</small></p>

                    {% if current_user.has_role('admin') %}
                        <p class="card-text"><small class="text-muted">
                        <a class="nav-link" href="{{ url_for('posts.edit_post', slug=post.slug)}}"><img src="https://img2.freepng.ru/20180420/bqq/kisspng-computer-icons-writing-fonts-vector-5ada38828ce8b3.0081536415242507545772.jpg" width="20" height="20" alt=""></a></small></p>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock  %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}


{% block  title %}
    {{post.title}}
{% endblock  %} 


{% block  content_title %}
    {{post.title}}
{% endblock  %} 


{% block  content %}
    <div class="tags">
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}"> <button type="button" class="btn btn-info btn-sm">{{ tag.name }}</button></a>
        {% endfor %}
    </div>
    {{ post.body }}
{% endblock  %} 

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block  title %}
    {{tag.name}} posts
{% endblock  %} 

{% block  content_title %}
<p class="font-weight-normal text-center">
    Посты с тэгом "{{tag.name}}" :
</p>
{% endblock  %} 

{% block  content %}

    {% for post in posts %}
    <div class="d-flex justify-content-center">
        <div class="card mb-3 shadow p-3 mb-5 bg-white rounded col md-offset-4 " style="max-width: 540px;">
            <div class="row">
                <div class="col-md-4 col">
                    <img src="https://mykaleidoscope.ru/uploads/posts/2019-12/1575766848_18-19.jpg" class="card-img"
                        alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body col-md-offset-4">
    
                        <h5 class="card-title">
                            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
                                <p class="font-weight-normal">{{ post.title }}</p>
                            </a>
                        </h5>
    
                        <p class="card-text">{{post.body}}</p>
                        <p class="card-text"><small class="text-muted">Изменен {{ post.created}}</small></p>
    
                        {% if current_user.has_role('admin') %}
                            <p class="card-text"><small class="text-muted">
                            <a class="nav-link" href="{{ url_for('posts.edit_post', slug=post.slug)}}"><img src="https://img2.freepng.ru/20180420/bqq/kisspng-computer-icons-writing-fonts-vector-5ada38828ce8b3.0081536415242507545772.jpg" width="20" height="20" alt=""></a></small></p>
                        {% endif %}
    
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock  %} 

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>

        {% block  title %}

        {% endblock  %} | Flask app

    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href=" {{ url_for('index') }}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">
                
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('posts.index') }}">My posts<span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    {% if current_user.has_role('admin') %}
                        <a class="nav-link" href="{{ url_for('posts.create_post') }}">+ New post</a>
                    {% endif %}
                </li>

                <li class="nav-item">
                    {% if current_user.has_role('admin') %}
                    <a class="nav-link" href="/admin">Admin</a>
                    {% endif %}
                </li>

            </ul>

            <form class="form-inline my-2 my-lg-0" method="GET">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q"
                    value="{{ request.args.get('q', '') }}">
                <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
            </form>

        </div>
    </nav>

    <div class="container">
        <p>
        <h1>

            {% block  content_title %}

            {% endblock  %}

        </h1>
        </p>
        <p>
            {% block  content %}

            {% endblock  %}
        </p>
    </div>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block  title %}

    Index page

{% endblock  %} 

{% block  content_title %}

<div class="container">
    <div class="row">
        <div class="col">
            <p class="text-center font-weight-normal">Главная страница</p>
        </div>
    </div>
</div>
{% endblock  %} 

{% block  content %}

    <p class="text-center font-weight-normal">Контент</p>

{% endblock  %} 

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-primary {{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

app/templates/security/login_user.html
{% extends 'base.html' %}

{% block title %}
    Вход
{% endblock %}

{% block content_title %}

  <!-- <div class="container">
    <div class="row">
        <div class="col">
            <h1 class="text-center font-weight-normal">Войти</h1>
        </div>
    </div>
</div> -->
  
{% endblock %}

{% block content %}
<br><br>
<div class="d-flex justify-content-center">
  <div class="shadow p-3 mb-5 bg-white rounded col-md-5 ">
      <div class="col-md-11 ">
        {% from "security/_macros.html" import render_field_with_errors, render_field %}
        {% include "security/_messages.html" %}
       
        <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
          <h1 class="text-center font-weight-normal">Войти</h1>
          {{ login_user_form.hidden_tag() }}
          {{ render_field_with_errors(login_user_form.email, class='form-control ') }}
          {{ render_field_with_errors(login_user_form.password, class='form-control') }}
          <div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="customSwitch1">
            <label class="custom-control-label " for="customSwitch1">Remember me</label>
          </div>
          {{ render_field(login_user_form.next) }}
          {{ render_field(login_user_form.submit, class="btn btn-outline-info ") }}
        </form>
      {% include "security/_menu.html" %}
    </div>
  </div>
</div>

{% endblock %}